[book]
authors = ["Dustin Firebaugh"]
language = "en"
multilingual = false
src = "src"
title = "Building Badge Apps"

[output.html]
default-theme="coal"
git-repository-url = "https://github.com/hackrva/badge2023"
git-repository-icon = "fa-github"
edit-url-template = "https://github.com/hackrva/badge2023/edit/main/web/docs/badgeappdev/{path}"
site-url = "/badge2023/badgeappdev/"
